Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(CValTest.py:11212): Gdk-CRITICAL **: 05:24:07.093: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Running 10000 games per value for c-val testing
Games for c-val of 0.500000 complete
Games for c-val of 0.600000 complete
Games for c-val of 0.700000 complete
Games for c-val of 0.800000 complete
Games for c-val of 0.900000 complete
Games for c-val of 1.000000 complete
Games for c-val of 1.100000 complete
Games for c-val of 1.200000 complete
Games for c-val of 1.300000 complete
Games for c-val of 1.400000 complete
Games for c-val of 1.500000 complete
Games for c-val of 1.600000 complete
Games for c-val of 1.700000 complete
Games for c-val of 1.800000 complete
Games for c-val of 1.900000 complete
Games for c-val of 2.000000 complete
Games for c-val of 2.100000 complete
Games for c-val of 2.200000 complete
Games for c-val of 2.300000 complete
Games for c-val of 2.400000 complete
Games for c-val of 2.500000 complete
{0.5: 4953, 0.6: 4931, 0.7: 4963, 0.8: 4919, 0.9: 4839, 1.0: 4911, 1.1: 4931, 1.2: 5033, 1.3: 4912, 1.4: 4905, 1.5: 4869, 1.6: 5013, 1.7: 4916, 1.8: 4977, 1.9: 4917, 2.0: 4947, 2.1: 4921, 2.2: 4883, 2.3: 4910, 2.4: 5020, 2.5: 4937}
